### ISSUE TITLE
Data update for 6.1.1

### ISSUE THREAD

**Issue by sdg-data-canada-odd-donnees** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#116]
New data available from the source.

**Comment by camereb** [comment]
Found provincial data from: https://www.sac-isc.gc.ca/eng/1614387410146/1614387435325

**Comment by MaiaPelletier** [comment]
12/15/2022: On hold until January so that we can report definite annual numbers.

**Comment by camereb** [comment]
Done in https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/commit/c113f4039e2ab22d0921acfbfc7641a2eb18559e

**Comment by MaiaPelletier** [comment]
2023 data needs to be removed

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/commit/4de98afecced0687d74646e3c28e295b9b728e90
