### ISSUE TITLE
Data Update 3.11.1

### ISSUE THREAD

**Issue by JulienSTC** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#140]
Data from 2010 to 2020 available here: https://opencanada.blob.core.windows.net/opengovprod/resources/1a833c68-0daa-440e-a8a2-a2e42d697c4b/english-pdf-5-english.pdf?sr=b&sp=r&sig=pfhGW9lYMCrnGgX7oEt3Dx4urKnFuTaRa9uP6O1hSc4%3D&sv=2015-07-08&se=2023-02-17T14%3A28%3A30Z

Also breakdown for sex is available for the same period.

**Comment by camereb** [comment]
I get an error when I try to open that link :/

**Comment by JulienSTC** [comment]
New link: https://open.canada.ca/data/en/dataset/17ee0902-055e-415e-b7aa-d9bee1734d35

**Comment by camereb** [comment]
Done in https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/commit/5a844760409edc9c746a1f0b014dcf1d06a78f37
