### ISSUE TITLE
Update 2.1.1

### ISSUE THREAD

**Issue by catherinemichaud** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#161]
New custom data for Territories here for 2020 https://www150.statcan.gc.ca/n1/en/daily-quotidien/221103/dq221103d-eng.pdf?st=XxwABUgE and look at note to users at end of document for 2019

**Comment by JulienSTC** [comment]
2021 now available: https://www150.statcan.gc.ca/n1/daily-quotidien/230621/dq230621c-eng.htm

**Comment by camereb** [comment]
Done in https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/commit/bfbec8e376e441e93d90b562cf49b7d1eb572f87
