### ISSUE TITLE
New data available 6.4.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#163]
Data for 2018-2020 period available: https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/water-quality-canadian-rivers.html

**Comment by camereb** [comment]
Done in https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/commit/bdc0034edb22755e955655ad3f5479a104189a7a
