### ISSUE TITLE
Add manual trigger for data updates 

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#164]
Add an event trigger in [refresh data workflow](https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/blob/develop/.github/workflows/refresh-indicator-data.yml) to allow for running data updates manually (maybe create data-update branch and workflow runs on every push to that branch)

**Comment by tristanmenard** [comment]
Done! daef5085e60f8b68c16af403bb929cbb3a983d6b

See steps to manually start data update action at https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow.
