### ISSUE TITLE
5.2.1 - Data Source udpates

### ISSUE THREAD

**Issue by sdg-data-canada-odd-donnees** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#171]
Old table for 5.2.1 has been archived, need to adjust automation code to take data from new table: https://www150.statcan.gc.ca/t1/tbl1/en/cv.action?pid=1410041601

New data source for federal judges: https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3510019801&cubeTimeFrame.startYear=2021&cubeTimeFrame.endYear=2022&referencePeriods=20210101%2C20220101

**Comment by tristanmenard** [comment]
The old judges table only has data for 2006,  2001, and 2016, while the new table has data for 2021-2023. Both are fairly limited ranges so do we prefer to combine these two sources together into a single data series or simply replace the old with the new?

**Comment by tristanmenard** [comment]
Another issue is that the statistics in the old table were divided for federal judges in one category and all provincial/territorial judges in another. Meanwhile, the new table is divided by court (e.g. All courts, Canada Courts, Federal Court of Appeals, Ontario Courts, Court of Appeal of Ontario). If desired, it would be possible to aggregate the values in the table to match the organization of the old one by combining the total numbers for all the provincial and territorial courts together.

**Comment by tristanmenard** [comment]
Now using a single data series for federally appointed judges (all courts) from the new judges table instead of two separate data series (one for federal, one for provincial) from the old judges table.
