### ISSUE TITLE
8.6.1 Data Hub

### ISSUE THREAD

**Issue by sdg-data-canada-odd-donnees** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#201]
Data for 2021 + 2022 have been released. Comments + Limitations should be updated for the prelim 2020-21 to "the latest 2 ref year"

CODR Table available at the link below. Indicator will need automation script. 

Statistics Canada. Table 36-10-0681-01  Environmental and Clean Technology Products Economic Account, employment and compensation per products category
DOI: https://doi.org/10.25318/3610068101-eng

https://www150.statcan.gc.ca/n1/pub/71-607-x/71-607-x2023016-eng.htm

**Comment by tristanmenard** [comment]
Merged to staging. CSV file will be updated whenever the next data update action is completed.
