### ISSUE TITLE
13.1.1 - Data Source Update

### ISSUE THREAD

**Issue by sdg-data-canada-odd-donnees** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#222]
Update data source link to: https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/greenhouse-gas-emissions.html
and the french : https://www.canada.ca/fr/environnement-changement-climatique/services/indicateurs-environnementaux/emissions-gaz-effet-serre.html

**Comment by tristanmenard** [comment]
Do we want to automate data acquisition for this indicator with a script that automatically retrieves and munges the dataset from https://data-donnees.az.ec.gc.ca/api/file?path=/substances%2Fmonitor%2Fcanada-s-official-greenhouse-gas-inventory%2FA-IPCC-Sector%2FEN_GHG_IPCC_Can_Prov_Terr.csv?

**Comment by tristanmenard** [comment]
Data source link for 13.1.1 now updated on develop branch (7036e1fb32b66963c33c400ccd8ad1456ea9c84f). URL text needs to be updated to match new data source.

**Comment by tristanmenard** [comment]
Merge to staging and production complete!
