### ISSUE TITLE
User Notices

### ISSUE THREAD

**Issue by JulienSTC** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#297]
Add user notice to front page, this should be added just below the middle section, but above the line. 

The file to modify for English: https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/blob/develop/translations/en/frontpage.yml. 

The file for the FR: https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/blob/develop/translations/fr/frontpage.yml

- [x] **EN**:
**User Notice**: Please note that updates will be applied to the website throughout summer 2024 to implement changes following the Canadian Indicator Framework strategic review. For more information, please consult the FAQ page.

- [x] **FR**: 
**Avis aux utilisateurs** : Veuillez noter que des mises à jour seront appliquées au site web tout au long de l'été 2024 afin de mettre en œuvre les changements consécutifs à l'examen stratégique du cadre canadien des indicateurs. Pour plus d'informations, veuillez consulter la page FAQ.

Add this section to the FAQ Page:

EN page: https://github.com/sdg-data-canada-odd-donnees/cif-cic_dev/blob/develop/_pages/faq.md
FR page: https://github.com/sdg-data-canada-odd-donnees/cif-cic_dev/blob/develop/_pages/fr/faq.md

- [x] **EN**: 
What is the Canadian Indicator Framework Strategic Review? 

Strategic Reviews of the Canadian Indicator Framework occur every three years following the implementation of the framework in 2021. Their purpose is to ensure the continued relevance of the ambitions, targets and indicators while ensuring the alignment of the Canadian Indicator Framework to other related frameworks. As such, strategic reviews will not substantially alter the scope, intent and coherence of the original indicator framework. 

- [x] **FR**:
Qu'est-ce que l'examen stratégique du cadre canadien d'indicateurs ? 

Les examens stratégiques du cadre canadien d'indicateurs ont lieu tous les trois ans après la mise en œuvre du cadre en 2021. Leur objectif est de garantir la pertinence continue des ambitions, des cibles et des indicateurs tout en assurant l'alignement du cadre canadien d'indicateurs sur d'autres cadres connexes. En tant que telles, les révisions stratégiques ne modifieront pas substantiellement la portée, l'intention et la cohérence du cadre d'indicateurs initial.

**Comment by Zelheim** [comment]
Done!
https://github.com/sdg-data-canada-odd-donnees/cif-cic_dev/pull/93
https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/pull/299
