### ISSUE TITLE
Data update for indicator 7.2.1

### ISSUE THREAD

**Issue by MaiaPelletier** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#55]
Data available for 2020

**Comment by MaiaPelletier** [comment]
Needs an automation script, methodology to be confirmed

**Comment by JulienSTC** [comment]
only 1 series needed, only the per capita should show and the progress measure should be added.

**Comment by MaiaPelletier** [comment]
- [ ] - Remove terajoules
- [ ] - Remove fuel type
- [ ] - Remove demand characteristics

**Comment by MaiaPelletier** [comment]
automated and updated in https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/commit/6f41ea733c2884b7e2549f26a0625af82ecfd915
