### ISSUE TITLE
Data update for 12.1.1

### ISSUE THREAD

**Issue by JulienSTC** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#76]
https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=2010002101

**Comment by MaiaPelletier** [comment]
Data updated in https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/commit/096b77f5e36ef935895f4ceb10db50ebb5daa4b0
