### ISSUE TITLE
data update for 13.1.1

### ISSUE THREAD

**Issue by JulienSTC** [sdg-data-canada-odd-donnees/cif-data-donnees-cic#77]
2020 now available

**Comment by MaiaPelletier** [comment]
Breakdown for regions: https://www.canada.ca/en/environment-climate-change/services/climate-change/greenhouse-gas-emissions/sources-sinks-executive-summary-2022.html

**Comment by MaiaPelletier** [comment]
done in https://github.com/sdg-data-canada-odd-donnees/cif-data-donnees-cic/commit/18c1af4912583fe90d4c73c6648971418658c443
